doc: fix client example adding _req arg in fn
With the following example in README.md, we have a compilation error:

```ocaml
let fn _meta _resp () = function
  | Some str -> print_string str
  | None -> ()

let () = Miou_unix.run @@ fun () ->
  let rng = Mirage_crypto_rng_miou_unix.(initialize (module Pfortuna)) in
  ignore(Httpcats.request ~fn ~uri:"https://google.com" ());
  Mirage_crypto_rng_miou_unix.kill rng
```

**The value fn has type  Httpcats.meta -> Httpcats.request -> unit -> string option -> unit but an expression was expected of type  'a Httpcats.handler =    Httpcats.meta ->    Httpcats.request -> Httpcats.response -> 'a -> string option -> 'a Type unit is not compatible with type Httpcats.response**.

We need to add **_req** argument in fn function, as following:

```ocaml


let fn _meta _req _resp () = function
  | Some str -> print_string str
  | None -> ()

let () = Miou_unix.run @@ fun () ->
  let rng = Mirage_crypto_rng_miou_unix.(initialize (module Pfortuna)) in
  ignore(Httpcats.request ~fn ~uri:"https://google.com" ());
  Mirage_crypto_rng_miou_unix.kill rng
```